import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({       
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <nav className="bg-orange-500 text-white px-8 py-4 flex justify-between items-center">
  <a href="/" className="text-2xl font-bold">
    Summer Essentials Store
  </a>

  <div className="flex items-center gap-6">
    <a href="/" className="hover:underline">Home</a>
    <a href="/" className="hover:underline">Products</a>
    <a href="/profile" className="hover:underline">My Profile</a>

    <a href="/login" className="bg-white text-orange-500 px-4 py-2 rounded">
      Login
    </a>
    <a href="/register" className="border border-white px-4 py-2 rounded">
      Register
    </a>
  </div>
</nav>

  {/* Main Content */}
  {children}

  <footer className="bg-gray-900 text-white mt-12 px-8 py-8">
  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
    <div>
      <h3 className="font-bold mb-2">Contact Info</h3>
      <p>Email: support@summerstore.com</p>
      <p>Phone: +880 1234 567890</p>
    </div>

    <div>
      <h3 className="font-bold mb-2">Social Links</h3>
      <p>Facebook | Instagram | Twitter</p>
    </div>

    <div>
      <h3 className="font-bold mb-2">Privacy Policy</h3>
      <p>Terms & Conditions</p>
      <p>Privacy Policy</p>
    </div>
  </div>

  <p className="text-center mt-6 text-gray-400">
    © 2026 Summer Essentials Store. All rights reserved.
  </p>
</footer>
</body>
    </html>
  );
}
